# Generated by Django 6.0.1 on 2026-02-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Trip duration in days', null=True),
        ),
    ]
