# Generated by Django 6.0.1 on 2026-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_motorcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motorcycle_type',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('cruiser', 'Cruiser'), ('touring', 'Touring'), ('adventure', 'Adventure'), ('naked', 'Naked/Standard'), ('dual_sport', 'Dual Sport'), ('scooter', 'Scooter'), ('cafe_racer', 'Cafe Racer'), ('scrambler', 'Scrambler'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Motorcycle',
        ),
    ]
